apiVersion: v1
kind: Service

metadata:
  name: kubernetes-experiments-service

spec:
  type: LoadBalancer
  selector:
    app: kubernetes-experiments
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
